markdown: kramdown
site_name: Google Docs user guide

nav:
  - About Google Docs: index.md
  - Create a document: Create.md
  - Download a file: Download.md
  - Print a document: Print.md
  - Manage access to a document: Manage.md
  - Manage page settings: Manages.md
  - Format text: Format.md
  - Add objects: Add.md
  - Manage add-ons: Manageadd.md


      
   
      

theme:
  name: material
  logo: '/img/logo.png'
  feature:
    tabs: false
  language: 'en'

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.extra
  - pymdownx.snippets:
      base_path: docs/src
    
plugins:
  - search

extra_css:
  - 'stylesheets/extra-page-content.css'
  - 'https://use.fontawesome.com/releases/v5.7.0/css/all.css'
  - 'https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css'
  
